#!/usr/bin/python

import os
import sys
import datetime
import time
import MySQLdb as db

sql_config = {
    "host": "xx.xx.xx.xx",
    "user": "username",
    "port": 3306,
    "db": "dbname",
    "passwd": "*****",
    "charset": "utf8"
}
table_name = sys.argv[1]

def add_partition(table_name):
    db_con = db.connect(**sql_config)
    db_cursor = db_con.cursor()
    for day_num in range(1,16):
        for hour in range(1,25):
            partnum = (datetime.datetime.now()+datetime.timedelta(hours=day_num*24+hour)).strftime("%Y%m%d%H")
            part_day = (datetime.datetime.now()+datetime.timedelta(seconds=day_num*24*3600+hour*3600+3600)).strftime("%Y-%m-%d %H:00:00")
            sql="ALTER TABLE " + table_name + " ADD PARTITION (PARTITION SYS_P" + str(partnum) + " VALUES LESS THAN (to_seconds(\'" + str(part_day) + "\')))";
            try:
                db_cursor.execute(sql)
                db_con.commit()
                print(sql)
            except Exception as e:
                print(sql)
                print(e)
                continue

if __name__ == "__main__":
    add_partition(table_name)
    print("partition created done")
